<label class="nodescr">iFrame app</label>
<input type="text" class="w250" name="config[app]" value="{$widget.config.app}" style="width:450px" id="appval"/>
<br>
<small>Leave blank to display main page</small>
<div class="clear"></div>

<br/>
<b>Note: You can customize your iFrame using cPanel apps</b><br/>
<br/>
<a href="#" onclick="$(this).hide();$('#apps-list').show();return false"><b>View available apps</b></a>
<div id="apps-list" style="padding:15px 0px;display:none;">

    <code class="app-el">Backups_Home</code>
    <code class="app-el">Calendar_Configure</code>
    <code class="app-el">ContactInfo_Change</code>
    <code class="app-el">Cron_Home</code>
    <code class="app-el">Database_MySQL</code>
    <code class="app-el">Database_phpMyAdmin</code>
    <code class="app-el">Domains_AddonDomains</code>
    <code class="app-el">Domains_SubDomains</code>
    <code class="app-el">Email_AccountLevelFiltering</code>
    <code class="app-el">Email_Accounts</code>
    <code class="app-el">Email_Archive</code>
    <code class="app-el">Email_Authentication</code>
    <code class="app-el">Email_AutoResponders</code>
    <code class="app-el">Email_BoxTrapper</code>
    <code class="app-el">Email_DefaultAddress</code>
    <code class="app-el">Email_DeliveryReport</code>
    <code class="app-el">Email_Forwarders</code>
    <code class="app-el">Email_GreyListing</code>
    <code class="app-el">Email_MailingLists</code>
    <code class="app-el">Email_MX</code>
    <code class="app-el">Email_SpamFilter</code>
    <code class="app-el">Email_UserLevelFiltering</code>
    <code class="app-el">FileManager_Home</code>
    <code class="app-el">Locale_Change</code>
    <code class="app-el">Password_Change</code>
    <code class="app-el">Site_Software</code>
    <code class="app-el">Site_Software_</code>
    <code class="app-el">Stats_AWStats</code>
    <code class="app-el">WHMCS_billing</code>
    <code class="app-el">add_a_dns_zone</code>
    <code class="app-el">add_an_a_entry_for_your_hostname</code>
    <code class="app-el">add_a_new_ip_address</code>
    <code class="app-el">add_a_package</code>
    <code class="app-el">additional_mysql_access_hosts</code>
    <code class="app-el">add_remove_recognized_ip_addresses</code>
    <code class="app-el">apache_configuration</code>
    <code class="app-el">apache_mod_userdir_tweak</code>
    <code class="app-el">apache_status</code>
    <code class="app-el">api_shell</code>
    <code class="app-el">api_tokens</code>
    <code class="app-el">apps_managed_by_appconfig</code>
    <code class="app-el">assign_ipv6_address</code>
    <code class="app-el">background_process_killer</code>
    <code class="app-el">backup_configuration</code>
    <code class="app-el">backup_restoration</code>
    <code class="app-el">backup_system_migration</code>
    <code class="app-el">backup_user_selection</code>
    <code class="app-el">basic_webhost_manager_setup</code>
    <code class="app-el">blocker</code>
    <code class="app-el">change_account_contact_email</code>
    <code class="app-el">change_hostname</code>
    <code class="app-el">change_log</code>
    <code class="app-el">change_multiple_sites_ip_addresses</code>
    <code class="app-el">change_mysql_user_password</code>
    <code class="app-el">change_ownership_of_an_account</code>
    <code class="app-el">change_ownership_of_multiple_accounts</code>
    <code class="app-el">change_root_password</code>
    <code class="app-el">change_sites_ip_address</code>
    <code class="app-el">change_webhost_manager_theme</code>
    <code class="app-el">cloudlinux_lve_manager</code>
    <code class="app-el">compiler_access</code>
    <code class="app-el">configuration_cluster</code>
    <code class="app-el">configure_application_locales</code>
    <code class="app-el">configure_cpanel_analytics</code>
    <code class="app-el">configure_cpanel_cron_jobs</code>
    <code class="app-el">configure_postgresql</code>
    <code class="app-el">configure_remote_service_ips</code>
    <code class="app-el">configure_security_policies</code>
    <code class="app-el">contact_manager</code>
    <code class="app-el">convert_addon_domain_to_account</code>
    <code class="app-el">copy_a_locale</code>
    <code class="app-el">copy_an_account_from_another_server_with_an_account_password</code>
    <code class="app-el">cpanel_development_forum</code>
    <code class="app-el">cpanel_log_rotation_configuration</code>
    <code class="app-el">cpanel_plugin_file_generator</code>
    <code class="app-el">cpanel_web_disk_configuration</code>
    <code class="app-el">cpanel_web_services_configuration</code>
    <code class="app-el">cphulk_brute_force_protection</code>
    <code class="app-el">create_a_new_account</code>
    <code class="app-el">create_support_ticket</code>
    <code class="app-el">customization</code>
    <code class="app-el">daily_process_log</code>
    <code class="app-el">database_map_tool</code>
    <code class="app-el">delete_a_dns_zone</code>
    <code class="app-el">delete_a_locale</code>
    <code class="app-el">delete_a_package</code>
    <code class="app-el">directoryindex_priority</code>
    <code class="app-el">dns_cluster</code>
    <code class="app-el">dns_server</code>
    <code class="app-el">easyapache_4</code>
    <code class="app-el">edit_a_locale</code>
    <code class="app-el">edit_a_package</code>
    <code class="app-el">edit_backup_mx_hosts</code>
    <code class="app-el">edit_blacklisted_smtp_ips</code>
    <code class="app-el">edit_dns_zone</code>
    <code class="app-el">edit_mx_entry</code>
    <code class="app-el">edit_only_verify_recipient_smtp_hosts</code>
    <code class="app-el">edit_questions_and_answers</code>
    <code class="app-el">edit_reseller_name_servers_and_privileges</code>
    <code class="app-el">edit_sender_verification_bypass_ips</code>
    <code class="app-el">edit_system_mail_preferences</code>
    <code class="app-el">edit_trusted_smtp_ips</code>
    <code class="app-el">edit_zone_templates</code>
    <code class="app-el">email_all_resellers</code>
    <code class="app-el">email_all_users</code>
    <code class="app-el">email_deliverability</code>
    <code class="app-el">enable_dkim_and_spf_globally</code>
    <code class="app-el">exim_configuration_manager</code>
    <code class="app-el">feature_manager</code>
    <code class="app-el">file_and_directory_restoration</code>
    <code class="app-el">forceful_server_reboot</code>
    <code class="app-el">force_password_change</code>
    <code class="app-el">ftp_server_configuration</code>
    <code class="app-el">ftp_server_proftpd_pureftpd</code>
    <code class="app-el">ftp_server_selection</code>
    <code class="app-el">generate_an_ssl_certificate_and_signing_request</code>
    <code class="app-el">global_configuration</code>
    <code class="app-el">graceful_server_reboot</code>
    <code class="app-el">grant_cpanel_support_access</code>
    <code class="app-el">greylisting</code>
    <code class="app-el">host_access_control</code>
    <code class="app-el">http_server_apache</code>
    <code class="app-el">imap_server</code>
    <code class="app-el">include_editor</code>
    <code class="app-el">initial_quota_setup</code>
    <code class="app-el">install_an_rpm</code>
    <code class="app-el">install_an_ssl_certificate_on_a_domain</code>
    <code class="app-el">install_a_perl_module</code>
    <code class="app-el">install_a_perl_module_process</code>
    <code class="app-el">install_cpaddons_site_software</code>
    <code class="app-el">ip_migration_wizard</code>
    <code class="app-el">ipv6_ranges</code>
    <code class="app-el">legacy_backup_configuration</code>
    <code class="app-el">legacy_language_file_upload</code>
    <code class="app-el">legacy_restore_backups</code>
    <code class="app-el">legacy_restore_multiple_backups</code>
    <code class="app-el">legacy_restore_multiple_backups_confirmation</code>
    <code class="app-el">limit_bandwidth_usage</code>
    <code class="app-el">list_accounts</code>
    <code class="app-el">list_parked_domains</code>
    <code class="app-el">list_subdomains</code>
    <code class="app-el">list_suspended_accounts</code>
    <code class="app-el">locale_editor</code>
    <code class="app-el">locale_xml_download</code>
    <code class="app-el">locale_xml_upload</code>
    <code class="app-el">log_rotation</code>
    <code class="app-el">mailbox_conversion</code>
    <code class="app-el">mail_delivery_reports</code>
    <code class="app-el">mailing_list_manager_mailman</code>
    <code class="app-el">mail_queue_manager</code>
    <code class="app-el">mailserver_configuration</code>
    <code class="app-el">mail_server_exim</code>
    <code class="app-el">mail_troubleshooter</code>
    <code class="app-el">manage_account_suspension</code>
    <code class="app-el">manage_autossl</code>
    <code class="app-el">manage_compiler_group</code>
    <code class="app-el">manage_cpaddons_site_software</code>
    <code class="app-el">manage_custom_rbls</code>
    <code class="app-el">manage_databases</code>
    <code class="app-el">manage_database_users</code>
    <code class="app-el">manage_demo_mode</code>
    <code class="app-el">manage_external_authentication</code>
    <code class="app-el">manage_external_authentication_providers</code>
    <code class="app-el">manage_external_authentication_users</code>
    <code class="app-el">manage_hooks</code>
    <code class="app-el">manage_mysql_profiles</code>
    <code class="app-el">manage_plugins</code>
    <code class="app-el">manage_resellers_ip_delegation</code>
    <code class="app-el">manage_resellers_shared_ip</code>
    <code class="app-el">manage_roots_ssh_keys</code>
    <code class="app-el">manage_services_ssl_certificates</code>
    <code class="app-el">manage_shell_access</code>
    <code class="app-el">manage_ssl_hosts</code>
    <code class="app-el">manage_wheel_group_users</code>
    <code class="app-el">market_provider_manager</code>
    <code class="app-el">memory_usage_restrictions</code>
    <code class="app-el">modify_an_account</code>
    <code class="app-el">modify_cpanel_whm_news</code>
    <code class="app-el">modify_upgrade_multiple_accounts</code>
    <code class="app-el">modsecurity_configuration</code>
    <code class="app-el">modsecurity_tools</code>
    <code class="app-el">modsecurity_vendors</code>
    <code class="app-el">module_installers</code>
    <code class="app-el">multiphp_ini_editor</code>
    <code class="app-el">multiphp_manager</code>
    <code class="app-el">mysql_mariadb_upgrade</code>
    <code class="app-el">mysql_root_password</code>
    <code class="app-el">nameserver_record_report</code>
    <code class="app-el">nameserver_selection</code>
    <code class="app-el">non_standard_locale_configuration</code>
    <code class="app-el">park_a_domain</code>
    <code class="app-el">password_modification</code>
    <code class="app-el">password_strength_configuration</code>
    <code class="app-el">perform_a_dns_cleanup</code>
    <code class="app-el">php_fpm_service_for_apache</code>
    <code class="app-el">phpMyAdmin</code>
    <code class="app-el">piped_log_configuration</code>
    <code class="app-el">process_manager</code>
    <code class="app-el">purchase_and_install_an_ssl_certificate</code>
    <code class="app-el">quota_modification</code>
    <code class="app-el">raw_apache_log_download</code>
    <code class="app-el">raw_ftp_log_download</code>
    <code class="app-el">rearrange_an_account</code>
    <code class="app-el">rebuild_rpm_database</code>
    <code class="app-el">rebuild_the_ip_address_pool</code>
    <code class="app-el">remote_access_key</code>
    <code class="app-el">repair_a_mysql_database</code>
    <code class="app-el">repair_mailbox_permissions</code>
    <code class="app-el">reseller_center</code>
    <code class="app-el">reserved_ips_editor</code>
    <code class="app-el">reset_account_bandwidth_limit</code>
    <code class="app-el">reset_a_dns_zone</code>
    <code class="app-el">reset_a_mailman_password</code>
    <code class="app-el">reset_resellers</code>
    <code class="app-el">resolver_configuration</code>
    <code class="app-el">restore_a_full_backup_cpmove_file</code>
    <code class="app-el">restore_modules_summary</code>
    <code class="app-el">review_transfers_and_restores</code>
    <code class="app-el">security_questions</code>
    <code class="app-el">server_information</code>
    <code class="app-el">server_profile</code>
    <code class="app-el">server_time</code>
    <code class="app-el">service_manager</code>
    <code class="app-el">service_status</code>
    <code class="app-el">setup_edit_domain_forwarding</code>
    <code class="app-el">set_zone_time_to_live_ttl</code>
    <code class="app-el">shell_fork_bomb_protection</code>
    <code class="app-el">show_accounts_over_quota</code>
    <code class="app-el">show_current_disk_usage</code>
    <code class="app-el">show_current_running_processes</code>
    <code class="app-el">show_edit_reserved_ips</code>
    <code class="app-el">show_ip_address_usage</code>
    <code class="app-el">show_mysql_processes</code>
    <code class="app-el">show_or_delete_current_ip_addresses</code>
    <code class="app-el">show_reseller_accounts</code>
    <code class="app-el">skeleton_directory</code>
    <code class="app-el">smtp_restrictions</code>
    <code class="app-el">software_development_kit</code>
    <code class="app-el">spamd_startup_configuration</code>
    <code class="app-el">sql_server_mysql</code>
    <code class="app-el">sql_server_pgsql</code>
    <code class="app-el">ssh_password_authorization_tweak</code>
    <code class="app-el">ssh_server_openssh</code>
    <code class="app-el">ssl_storage_manager</code>
    <code class="app-el">statistics_software_configuration</code>
    <code class="app-el">support_center</code>
    <code class="app-el">synchronize_dns_records</code>
    <code class="app-el">system_update</code>
    <code class="app-el">task_queue_monitor</code>
    <code class="app-el">terminal</code>
    <code class="app-el">terminate_accounts</code>
    <code class="app-el">theme_manager</code>
    <code class="app-el">tomcat_manager</code>
    <code class="app-el">traceroute_enable_disable</code>
    <code class="app-el">transfer_tool</code>
    <code class="app-el">tweak_settings</code>
    <code class="app-el">two_factor_authentication</code>
    <code class="app-el">unsuspend_bandwidth_exceeders</code>
    <code class="app-el">update_database_map</code>
    <code class="app-el">update_database_map_process</code>
    <code class="app-el">update_preferences</code>
    <code class="app-el">update_server_software</code>
    <code class="app-el">upgrade_downgrade_an_account</code>
    <code class="app-el">upgrade_to_latest_version</code>
    <code class="app-el">view_available_locales</code>
    <code class="app-el">view_bandwidth_usage</code>
    <code class="app-el">view_mail_statistics_summary</code>
    <code class="app-el">view_relayers</code>
    <code class="app-el">view_reseller_usage_and_manage_account_status</code>
    <code class="app-el">view_sent_summary</code>
    <code class="app-el">web_template_editor</code>
</div>
{literal}
    <style type="text/css">
        .app-el {
            padding: 2px 5px;
            font-size: 11px;
            cursor: pointer;
            text-shadow: 0 1px 0 #FFFFFF;
            border: 1px #BBBBBB solid;
            background: #f2f2f2;
            float: left;
            margin-right: 10px;
            margin-top: 3px;
            color: #464646;
            border-radius: 4px;
        }
        .app-el:hover {
            border-color: #666;
        }
    </style>
    <script type="text/javascript">
        $('.app-el').click(function () {
            $('#appval').val($.trim($(this).text())).focus();
            return false;
        });
    </script>
{/literal}