---
redirecturl:
  value: 
  name: Redirect URL
  description: ใส่ " {CMS_URL}/microsoft-365 " เพื่อ Redirect ไปยังหน้าอื่น เช่น https://netway.co.th/microsoft-365 
  type: input  
forceredirect:
  value: 0
  name: Force Redirect URL
  description: Make sure want to redirect for everyone can see the product page.
  type: checkbox  
carttemplate:
  value: domain_2019/domain_2019
ownsummarypage:
  value: 1
template:
  value: hide
rows_limit:
  value: 1
  name: Visible domain rows
  description: Enter the number of rows visible after the search. Showing more domains is avaliable by clicking the "Load more" button
  type: input
fullscreen:
  value: 1
  name: Full-screen
  description: Enable full-screen mode
  type: checkbox
spotlight:
  value: 1
  name: Enable spotlight
  type: checkbox
  description: It will display domains with 'featured' tag
custdescription:
  value: 1
  name: Slogan
  description: You can edit it in templates/orderpages/domain_2019/widgets/description.tpl
  type: checkbox
pricing:
  value: 1
  name: Pricing table
  description:
  type: checkbox
disable_transfer:
  value: 0
  name: Disable domain transfer
  type: checkbox
disable_bulk_transfer:
  value: 0
  name: Disable bulk domain transfer
  type: checkbox