{*
@@author:: HostBill team
@@name:: Slideshow based on Slider plugin
@@description:: Use slides generated by HostBill Slider plugin as your orderpage<br/>See <a href="http://hostbillapp.com/features/apps/hb_slider.html" target="_blank">http://hostbillapp.com/features/apps/hb_slider.html</a> for more details, configuration options<br/>
@@thumb:: cart_slideshow/thumb.png
@@img:: cart_slideshow/big.png
*}
<script type="text/javascript" src="{$orderpage_dir}common/cart.js?step={$step}"></script>
{include file='cart.progress.tpl'}


{if $step==0}
{include file='cart0_slideshow.tpl'}

{elseif $step==1}
	{include file='cart1.tpl'}
{elseif $step==2}
	{include file='cart2.tpl'}
{elseif $step==3}
	{include file='cart3.tpl'}
{elseif $step==4}
	{include file='cart4.tpl'}
{elseif $step==5}
	{include file='cart5.tpl'}
{/if}