---
productfeatures:
  value: ulli+spec
imgpreview:
  value: '../templates/orderpages/comparetable/howto.png'
  name: View editable areas
  type: link
selected:
  value: 1
  name: Highlight plan selection 
  description: Enter a number to highlight one of your products, '0' refers to first
  type: input
customheader:
  value: 'HostBill Advantages:'
  name: Custom header
  type: input
firstblock:
  value: |
          <h2>100%</h2>
          <h3>Server Stability</h3>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          <a href="#" >Read More &raquo;</a>
  name: First block
  description: Left most block, html available
  type: textarea
secondblock:
  value: |
          <h2>24 hour</h2>
          <h3>User support</h3>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          <a href="#" >Read More &raquo;</a>
  name: Second block 
  description: Middle block, html available
  type: textarea
thirdblock:
  value: |
          <h2>Lifetime</h2>
          <h3>Quarantee for all</h3>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          <a href="#" >Read More &raquo;</a>
  name: Third block 
  description: Right most block, html available
  type: textarea
footer:
  value: <strong>Not happy with our plans?</strong> Don't worry! Write to us for a personalized plan that fits your needs. <a href="?cmd=tickets&action=new" >Write to us &raquo;</a>
  name: Cart Footer
  description: Html available
  type: textarea
  