---
productfeatures:
  value: ulli+description+
imgpreview:
  value: '../templates/orderpages/cart_fancycomparison/howto.png'
  name: View editable areas
  type: link 
header:
  value: Configure whatever you desire
  name: Header
  description: This phrase will be displayed right above category packages
  type: input
subheader:
  value: Fast. One-click. Cheap. For you!
  name: Sub-header
  description: Displayed below main header
  type: input
plandesc:
  name: Package descriptions
  description: Short description displayed under product price
  value: |
          <li>Perfect for starting, nice price and great options.</li>
          <li>Great for advanced plans and fast servers.</li>
          <li>The most popular!</li>
          <li>The most complete plan of all, everything included!</li>
  type: featurelist
ribbon:
  value: 2
  name: Display ribbon
  description: Package namber, 0 means first
  type: input
footer1head:
  value: 24h Support
  name: Left block header
  description: This phrase will be displayed below package list
  type: input
footer1text:
  name: Left block text
  type: textarea
  value: HostBill helps run online businesses for companies all over the world. Our online forums is great meeting point for current and future users to exchange tips, opinions and ideas.
footer1url:
  value: '#'
  name: Right block link url
  type: input
footer2head:
  value: 30 days tech-support
  name: Right block header
  description: This phrase will be displayed below package list
  type: input
footer2text:
  name: Right block text
  type: textarea
  value: HostBill helps run online businesses for companies all over the world. Our online forums is great meeting point for current and future users to exchange tips, opinions and ideas.
footer2url:
  value: '#'
  name: Right block link url
  type: input