---
productfeatures:
  value: ulli+features
imgpreview:
  value: '../templates/orderpages/flexboxes/cart_flexboxes_howto.png'
  name: View editable areas
  type: link
promotext:
  value: 'Use promo code: <span>XXXXXXX</span> to get 50% off for 1 year signup* '
  name: Promotion text
  description: Its a good place to put promotional code.
  type: input
redstriptext:
  value: '<span class="tab-or1">50%</span><span class="tab-or2">off <br>1 year</span>'
  name: Red strip text
  description: Use this to draw more attention to your plan
  type: input