---
imgpreview:
  value: '../templates/orderpages/fourbox/cart_slidersquare_fourbox.png'
  name: View editable areas
  type: link
footertext:
  value: '<strong>Enterprise Customers:</strong> Contact us to discuss special offers for higher feature volumes'
  name: Footer phrase text
  description: This phrase will be displayed below available packages
  type: input
bestline:
  value: Best service at affordable price
  name: Header phrase
  description: This will be displayed next to company name
  type: input
phoneline:
  value: 'Call: +01 123 456 67'
  name: Company phonenumber
  description: This will be displayed on top right side
  type: input
whyourplantext:
  value: 'About our plan'
  name: About our plan header
  type: input
whyourplan:
  value: |
         <ul><li class='i1'><h2>Free server!</h2>
								<ul>
									<li class='j1'>Set unlimited free websites</li>
									<li class='j2'>Automated signup for your clients</li>
									<li class='j3'>Manage sites with one login</li>
								</ul>
							</li>
							<li class='i2'>
								<h2>No money</h2>
								<ul>
									<li class='j1'>Set unlimited free websites</li>
									<li class='j2'>Automated signup for your clients</li>
									<li class='j3'>Manage sites with one login</li>
								</ul>
							</li>
							<li class='i3'>
								<h2>PayPal friendly</h2>
								<ul>
									<li class='j1'>Set unlimited free websites</li>
									<li class='j2'>Automated signup for your clients</li>
									<li class='j3'>Manage sites with one login</li>
								</ul>
							</li>
							<li class='i4'>
								<h2>PayPal friendly</h2>
								<ul>
									<li class='j1'>Set unlimited free websites</li>
									<li class='j2'>Automated signup for your clients</li>
									<li class='j3'>Manage sites with one login</li>
								</ul>
							</li>
						</ul><div class='clear'></div>
  name: About our plan
  description: HTML allowed, explain why your customer should choose you.
  type: textarea
aboutus:
  value: |
         <h1>About company</h1>
         <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
  name: About our company text
  description: Displayed in orderpage footer.
  type: textarea