---
productfeatures:
  value: ulli+spec
imgpreview:
  value: '../templates/orderpages/onestep_packsliders/howto.png'
  name: View editable areas
  type: link
description:
  value: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book
  name: Description
  type: input
subheader1:
  value: chose best options
  name: Select yor plan sub-header
  type: input
subheader2:
  value: choose desired payment method
  name: Payment sub-header
  type: input
subheader3:
  value: your personal details
  name: Client info sub-header
  type: input