---
productfeatures:
  value: ulli+spec
imgpreview:
  value: '../templates/orderpages/onestep_comparison_boxes/howto.png'
  name: View editable areas
  type: link
footer:
  value: Checkout
  name: Footer 
  type: input
subfooter:
  value: |
          Not happy with our plans? Don't worry! Write to us for a personalized plan that fits your needs. <a href="?cmd=tickets&action=new" >Write to us &raquo;</a>
  name: Sub-footer 
  type: textarea
footertext:
  value: |
         <strong>Need something special?</strong><br />
         HostBill lets you choose a template for every order page you have. You can create your own Order Page template or use one from templates that come with HostBill.
  name: Footer Description
  description: HTML is allowed.
  type: textarea