---
imgpreview:
  value: '../templates/orderpages/onestep_gauge/howto.png'
  name: View editable areas
  type: link
description:
  value: 'Customize Your <strong><span class="blue">Perfect</span> Plan</strong>'
  name: Header
  type: input
whyus1:
  value: |
        <h3>Suport for any language</h3>
        HostBill can support all kind of languages, we have over 15 different languages you can install...
  name: First Block
  type: textarea
  description: First leftmost block. HTML is allowed.
whyus2:
  value: |
        <h3>Supported Domains Registrars</h3>
        Domain registration and management is easy. We support more than 20 Domain Registrars. 
  name: Second Block
  type: textarea
  description: First rightmost  block. HTML is allowed.
whyus3:
  value: |
         <h3>70+ payment gateways</h3>
         Create invoice and send to client. HostBill supports more than 70+ payment gateways.
  name: Third Block
  description: Second leftmost block. HTML is allowed.
  type: textarea
whyus4:
  value: |
        <h3>Security</h3>
        Security is critical. We are working on tweaking code, finding vulnerabilities and more.
  name: Fourth Block
  type: textarea
  description: Second rightmost  block. HTML is allowed.
aboutus:
  value: ?cmd=knowledgebase
  name: About us - Link
  type: textarea
  description: Second rightmost  block. HTML is allowed.