---
template:
  value: hide
imgpreview:
  value: '../templates/orderpages/onestep_simple/howto.png'
  name: View editable areas
  type: link 
righttext:
  name: Right side text
  description: This phrase will be displayed on the right side above cart summary
  type: textarea
  value: |
   <b>You can easily add/edit/remove text placed here:</b> 
   <strong>Using orderpage configuration in admin panel</strong>
   Settings &raquo; Products & Services &raquo; 'Orderpagename' &raquo; Customize!
   <strong>Over 205,000 customers worldwide</strong> Hundreds are joining every day.
   <strong>5-star customer service</strong> 
   Fast & friendly help (phone, email & live-chat)
tostext:
  value: Edit this text in order page configuration - notify your customers about additional Terms of Service/Acceptable use policy in your company.
  name: Terms of Service
  description: This phrase will be displayed right above order submit button, and below TOS checkbx
  type: textarea