---
productfeatures:
  value: ulli+spec
imgpreview:
  value: '../templates/orderpages/nestep_fancy/howto.png'
  name: View editable areas
  type: link
lighter:
  value: #ababab
  name: First color
  type: colorpicker
  description: Color used for highlights and as top gradient value
darker:
  value: #fbabab
  name: Second color
  type: colorpicker
  description: Color used for price, buttons and as bottom gradient value
description:
  value: |
         <h1>Need something special?</h1>
         <p><i>
         HostBill lets you choose a template for every order page you have. You can create your own Order Page template or use one from templates that come with HostBill.
         </i></p>
  name: Custom Description
  description: HTML is allowed.
  type: textarea