---
redirecturl:
  value: 
  name: Redirect URL
  description: ใส่ " {CMS_URL}/microsoft-365" เพื่อ Redirect  ไปยังหน้าอื่น เช่น https://netway.co.th/microsoft-365 
  type: input
forceredirect:
  value: 0
  name: Force Redirect URL
  description: Make sure want to redirect for everyone can see the product page.
  type: checkbox
productfeatures:
  value: ulli+spec
headertext:
  value: |
    Setup your new server
  name: Header text
  type: input
subheadertext:
  value: |
    Quickly setup your prefered plan and start your new business.
  name: Sub-header text
  type: input
show_parent_category_contents:
  value: 0
  name: 'Show parent category contents'
  type: checkbox
country_flag:
  value: 'none'
  name: 'Country flag'
  type: countryflag