---
redirecturl:
  value: 
  name: Redirect URL
  description: ใส่ " {CMS_URL}/microsoft-365 " เพื่อ Redirect ไปยังหน้าอื่น เช่น https://netway.co.th/microsoft-365 
  type: input
forceredirect:
  value: 0
  name: Force Redirect URL
  description: Make sure want to redirect for everyone can see the product page.
  type: checkbox
productfeatures:
  value: ulli+spec
imgpreview:
  value: '../templates/orderpages/onestep_cloud_2019/howto.png'
  name: View editable areas
  type: link
headertext:
  value: |
         Setup your server within minutes
  name: Header text
  type: input
subheadertext:
  value: |
         Quickly setup your prefered plan and start your new business.
  name: Sub-header text
  type: input
show_reccuring_price_instead_today:
  value: 1
  name: 'Show the monthly price instead of the `today` price in the bottom bar. Other prices will be shown in the tooltip box'
  type: checkbox
hide_product_choosing:
  value: 1
  name: 'Remove product choosing if only one product is available'
  type: checkbox
show_features:
  value: 1
  name: 'Show additional features for products'
  type: checkbox
scroll_to_configuration:
  value: 1
  name: 'Automatic scrolling for configuration after selecting the product'
  type: checkbox
show_parent_category_contents:
  value: 0
  name: 'Show parent category contents'
  type: checkbox
show_cycles_in_summary:
    value: 0
    name: 'Show billing cycles in summary'
    type: checkbox
country_flag:
  value: 'none'
  name: 'Country flag'
  type: countryflag
simple_field_for_registering:
  value: 0
  name: Simple field for domain registering
  type: checkbox