#!/bin/bash
#
#       /etc/rc.d/init.d/sslsoapserv
#
# Starts the sslsoapserv daemon
#
# chkconfig: - 2345 15 80
# description: Service to Connect Symantec SSL API SERVER
# processname: sslsoapserv
# pidfile: /tmp/sslsoapserv.pid

### BEGIN INIT INFO
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Start priority should be 15
# Stop priority should be 80
### END INIT INFO


# Source function library.

. /etc/init.d/functions

RETVAL=0
prog="Service to Connect Symantec SSL API SERVER"
APP_BIN="/home/rvglobal/sslsoapserv/sslsoapserv"

if [ ! -x ${APP_BIN} ] ; then
        echo -n "${APP_BIN} not installed! "
        # Tell the user this has skipped
        exit 5
fi

start() {
        echo -n $"Starting $prog: "
        daemon $APP_BIN &
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/sslsoapserv
        echo
}

stop() {
        echo -n $"Stopping $prog: "
        killproc /usr/bin/python $APP_BIN
        RETVAL=$?
        rm -f /var/lock/subsys/sslsoapserv
        echo
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  reload|restart)
        stop
        sleep 10
        start
        RETVAL=$?
        ;;
  condrestart)
        if [ -f /var/lock/subsys/sslsoapserv ]; then
            stop
            start
        fi
        ;;
  status)
        status $APP_BIN
        RETVAL=$?
        ;;
  *)
        echo $"Usage: $0 {condrestart|start|stop|restart|reload|status}"
        exit 1
esac

exit $RETVAL
